// ═══════════════════════════════════════════════
// STRAIN DATABASE (LOCAL)
// ═══════════════════════════════════════════════
const STRAIN_DB = {
  // --- A ---
  "og kush": { name: "OG Kush", type: "hybrid", lineage: "Chemdawg x Hindu Kush", terpenes: "Mirceno, Limoneno, Cariofileno", thc: "19-26%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Relaxante, Eufórico", aromas: "Pinho, Terra, Cítrico", description: "Clássica mundial, aroma terroso e efeito potente.", growTip: "Gosta de clima seco e LST.", medicalNote: "Estresse e insônia." },
  "haze": { name: "Original Haze", type: "sativa", lineage: "", terpenes: "", thc: "16-20%", cbd: "< 1%", flowerWeeks: "12-14 semanas", effects: "Criativo, Energético", aromas: "Cítrico, Picante", description: "Base de muitas sativas. Ciclo longo, efeito cerebral puro.", growTip: "Cresce muito, use SCROG.", medicalNote: "Depressão e fadiga." },
  "amnesia haze": { name: "Amnesia Haze", type: "sativa", lineage: "(Afghani x Hawaiian) x (Laos x Jamaica)", terpenes: "Mirceno", thc: "20-25%", cbd: "< 1%", flowerWeeks: "10-12 semanas", effects: "Eufórico, Energético", aromas: "Limão, Terroso", description: "Sativa potente, sabor cítrico marcante.", growTip: "Sensível a pragas, ventilação firme.", medicalNote: "Foco e criatividade." },
  "ak-47": { name: "AK-47", type: "sativa-dominant", lineage: "", terpenes: "", thc: "17-23%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Feliz, Relaxado", aromas: "Terroso, Especiarias", description: "Apesar do nome, é suave e criativa.", growTip: "Odor forte, use filtros excelentes.", medicalNote: "Insônia e ansiedade." },
  "afghan kush": { name: "Afghan Kush", type: "indica", lineage: "", terpenes: "", thc: "15-20%", cbd: "1%", flowerWeeks: "7-8 semanas", effects: "Relaxamento profundo", aromas: "Haxixe, Terra", description: "Resinosa e robusta, vinda das montanhas.", growTip: "Muito resistente a mofo.", medicalNote: "Analgesia e sono." },
  "amnesia auto": { name: "Amnesia Auto", type: "sativa-dominant", lineage: "", terpenes: "", thc: "16-19%", cbd: "< 1%", flowerWeeks: "10-11 semanas (total)", effects: "Eufórico, Mental", aromas: "Incenso, Limão", description: "Clássica sativa em versão rápida.", growTip: "Gosta de luz intensa.", medicalNote: "Fadiga crônica." },
  // --- B ---
  "blue dream": { name: "Blue Dream", type: "sativa-dominant", lineage: "Blueberry x Haze", terpenes: "Mirceno, Pineno, Limoneno", thc: "17-24%", cbd: "1-2%", flowerWeeks: "9-10 semanas", effects: "Criativo, Relaxante", aromas: "Mirtilo, Doce", description: "Equilíbrio perfeito entre corpo e mente.", growTip: "Cuidado com oídio no final.", medicalNote: "Dores sem sedação." },
  "bubba kush": { name: "Bubba Kush", type: "indica", lineage: "", terpenes: "", thc: "15-22%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Sonolento, Relaxado", aromas: "Café, Chocolate", description: "Indica pesada para descanso profundo.", growTip: "Planta baixa, ótima para espaços pequenos.", medicalNote: "Insônia e espasmos." },
  "bruce banner": { name: "Bruce Banner", type: "hybrid", lineage: "OG Kush x Strawberry Diesel", terpenes: "Cariofileno, Mirceno, Limoneno", thc: "24-29%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Incrível energia, Feliz", aromas: "Diesel, Morango", description: "Potência verde explosiva.", growTip: "Pode ser esticada na flora.", medicalNote: "Fadiga e dor severa." },
  "blueberry": { name: "Blueberry", type: "indica-dominant", lineage: "Purple Thai x Thai x Afghani", terpenes: "Mirceno, Cariofileno, Pineno", thc: "16-24%", cbd: "< 1%", flowerWeeks: "7-9 semanas", effects: "Feliz, Relaxado", aromas: "Baga, Doce", description: "Ícone dos anos 70, sabor de mirtilo.", growTip: "Resistente, fica roxa com frio.", medicalNote: "Relaxamento muscular." },
  "biscotti": { name: "Biscotti", type: "indica-dominant", lineage: "", terpenes: "", thc: "25-28%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Criativo, Relaxado", aromas: "Biscoito, Gasolina", description: "Sabor de padaria e visual roxo escuro.", growTip: "Gosta de ambientes estáveis.", medicalNote: "Bem-estar mental." },
  "black domina": { name: "Black Domina", type: "indica", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Sedativo, Pesado", aromas: "Pimenta, Terra", description: "Híbrida de 4 linhagens clássicas indica.", growTip: "Planta muito escura, resistente.", medicalNote: "Insônia severa." },
  // --- C ---
  "chemdawg": { name: "Chemdawg", type: "hybrid", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Mental, Relaxado", aromas: "Diesel, Químico", description: "Aroma de combustível inconfundível.", growTip: "Mantenha a ventilação impecável.", medicalNote: "Dores e depressão." },
  "critical": { name: "Critical", type: "hybrid", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Fome, Relaxado", aromas: "Doce, Skunk", description: "Famosa pela rapidez e alta produção.", growTip: "Perfeita para SOG.", medicalNote: "Falta de apetite." },
  "critical kush": { name: "Critical Kush", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-25%", cbd: "1-2%", flowerWeeks: "8-9 semanas", effects: "Pesado, Relaxante", aromas: "Ervas, Terra", description: "Junção de Critical com OG Kush.", growTip: "Produz muitos cristais.", medicalNote: "Alívio de dor." },
  "cookies and cream": { name: "Cookies and Cream", type: "hybrid", lineage: "", terpenes: "", thc: "20-26%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Eufórico, Relaxado", aromas: "Doce, Baunilha", description: "Destaque nos dispensários, resina densa.", growTip: "Gosta de nutrientes abundantes.", medicalNote: "Estresse diário." },
  "candy kush": { name: "Candy Kush", type: "hybrid", lineage: "", terpenes: "", thc: "18-22%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Feliz, Elevado", aromas: "Doce, Frutado", description: "Sabor adocicado e efeito equilibrado.", growTip: "Fácil de cultivar.", medicalNote: "Humor baixo." },
  // --- D ---
  "durban poison": { name: "Durban Poison", type: "sativa", lineage: "Landrace (Durban, South Africa)", terpenes: "Terpinoleno, Mirceno, Ocimeno", thc: "15-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Focado, Energético", aromas: "Doce, Picante", description: "Sativa pura sul-africana, energética.", growTip: "Gosta de calor e sol pleno.", medicalNote: "Fadiga e foco." },
  "do-si-dos": { name: "Do-Si-Dos", type: "indica-dominant", lineage: "", terpenes: "", thc: "25-30%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Total relaxamento", aromas: "Doce, Terra", description: "Poderosa indica de visual escuro.", growTip: "Mantenha a umidade baixa na flora.", medicalNote: "Dor crônica." },
  "diesel": { name: "NYC Diesel", type: "sativa-dominant", lineage: "", terpenes: "", thc: "18-22%", cbd: "< 1%", flowerWeeks: "10-11 semanas", effects: "Social, Elevado", aromas: "Toranja, Diesel", description: "Sativa cítrica com aroma pungente.", growTip: "Pode ser alta, controle altura.", medicalNote: "Ansiedade social." },
  // --- E ---
  "euphoria": { name: "Euphoria", type: "indica-dominant", lineage: "", terpenes: "", thc: "9%", cbd: "10%", flowerWeeks: "8 semanas", effects: "Social, Relaxado", aromas: "Doce, Frutado", description: "Alta em CBD, efeito suave e medicinal.", growTip: "Compacta e resistente.", medicalNote: "Ansiedade e inflamação." },
  // --- F ---
  "forbidden fruit": { name: "Forbidden Fruit", type: "indica-dominant", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Fome, Relaxado", aromas: "Cereja, Tropical", description: "Visual roxo escuro, visual deslumbrante.", growTip: "Muito resistente a mofo.", medicalNote: "Falta de apetite." },
  // --- G ---
  "gelato": { name: "Gelato #33", type: "hybrid", lineage: "Sunset Sherbet x Thin Mint GSC", terpenes: "Cariofileno", thc: "20-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Eufórico, Relaxado", aromas: "Cremoso, Doce", description: "Famosa 'Larry Bird', sabor de sobremesa.", growTip: "Sensível a excesso de luz no final.", medicalNote: "Bem-estar profundo." },
  "girl scout cookies": { name: "Girl Scout Cookies (GSC)", type: "indica-dominant", lineage: "OG Kush x Durban Poison", terpenes: "Cariofileno", thc: "25-28%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Relaxo físico pesado", aromas: "Menta, Doce", description: "Linhagem Cookies original, muito potente.", growTip: "Dê cálcio extra para as raízes.", medicalNote: "Estimulante de apetite." },
  "gorilla glue": { name: "Gorilla Glue #4 (GG4)", type: "hybrid", lineage: "Sour Dubb x Chem's Sister x Chocolate Diesel", terpenes: "Cariofileno, Mirceno, Limoneno", thc: "25-30%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Colado no sofá", aromas: "Pungente, Pinheiro", description: "Tanta resina que cola as tesouras.", growTip: "Estica muito nas duas primeiras semanas de flora.", medicalNote: "Espasmos e dor forte." },
  "granddaddy purple": { name: "Granddaddy Purple (GDP)", type: "indica", lineage: "Mendo Purps x Skunk x Afghanistan", terpenes: "Mirceno, Cariofileno, Pineno", thc: "17-23%", cbd: "< 1%", flowerWeeks: "8-11 semanas", effects: "Soninho, Feliz", aromas: "Uva, Baga", description: "Ícone roxo de relaxamento profundo.", growTip: "Buds densos, cuidado com bolor.", medicalNote: "Insônia e dores." },
  "green crack": { name: "Green Crack", type: "sativa", lineage: "Skunk #1 x Unknown Afghani Indica", terpenes: "Mirceno, Cariofileno, Pineno", thc: "15-20%", cbd: "< 1%", flowerWeeks: "7-9 semanas", effects: "Energético, Focado", aromas: "Manga, Frutado", description: "Sativa pura para o dia todo.", growTip: "Gosta de luz, sensível a oídio.", medicalNote: "Fadiga matinal." },
  "ghost train haze": { name: "Ghost Train Haze", type: "sativa", lineage: "", terpenes: "", thc: "25-28%", cbd: "< 1%", flowerWeeks: "11-13 semanas", effects: "Criativo, Alerta", aromas: "Floral, Cítrico", description: "Extrema potência sativa.", growTip: "Floração longa, sega protocolo.", medicalNote: "Depressão crônica." },
  // --- H ---
  "headbanger": { name: "Headbanger", type: "sativa-dominant", lineage: "Sour Diesel x Biker Kush", terpenes: "Cariofileno, Limoneno, Linalol", thc: "21-28%", cbd: "< 1%", flowerWeeks: "10-12 semanas", effects: "Foco total, Eufórico", aromas: "Diesel, Ácido", description: "Combustível cítrico potente. Vencedora da Cup.", growTip: "Pede redes (SCROG).", medicalNote: "Estresse e enxaqueca." },
  "hindu kush": { name: "Hindu Kush", type: "indica", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Calmo, Centrado", aromas: "Sândalo, Terra", description: "Indica original das montanhas.", growTip: "Planta densa e pequena.", medicalNote: "Alívio de tensão." },
  // --- I ---
  "ice": { name: "ICE", type: "hybrid", lineage: "", terpenes: "", thc: "18-21%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Físico, Relaxado", aromas: "Fresco, Pinheiro", description: "Resina que parece gelo sobre os buds.", growTip: "Ótima para extrações.", medicalNote: "Náuseas." },
  // --- J ---
  "jack herer": { name: "Jack Herer", type: "sativa-dominant", lineage: "Haze x Northern Lights #5 x Shiva Skunk", terpenes: "Terpinoleno", thc: "18-24%", cbd: "< 1%", flowerWeeks: "8-10 semanas", effects: "Elevado, Criativo", aromas: "Madeira, Especiarias", description: "Homenagem ao imperador do cânhamo.", growTip: "Solo rico em micronutrientes.", medicalNote: "Humor baixo." },
  // --- K ---
  "kali mist": { name: "Kali Mist", type: "sativa", lineage: "", terpenes: "", thc: "18-22%", cbd: "< 1%", flowerWeeks: "10-12 semanas", effects: "Cerebral puro", aromas: "Ervas, Incenso", description: "A rainha das sativas, pouco folhosa.", growTip: "Facil de cultivar para sativa.", medicalNote: "Dores menstruais." },
  "kosher kush": { name: "Kosher Kush", type: "indica", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Sedação pesada", aromas: "Frutado, Terroso", description: "Muitas vezes ganhadora da Cannabis Cup.", growTip: "Gosta de alimentação pesada.", medicalNote: "Insônia severa." },
  // --- L ---
  "lemon haze": { name: "Lemon Haze", type: "sativa-dominant", lineage: "", terpenes: "", thc: "17-22%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Social, Feliz", aromas: "Limão siciliano", description: "Cítrica refrescante e ativa.", growTip: "Regule o pH com precisão.", medicalNote: "Fadiga e tédio." },
  "la confidential": { name: "LA Confidential", type: "indica", lineage: "", terpenes: "", thc: "19-25%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Psicodélico, Físico", aromas: "Pinho, Terroso", description: "Clássica de LA, muito resinosa.", growTip: "Resistente e compacta.", medicalNote: "Dores e espasmos." },
  "lsd": { name: "LSD", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-24%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Visual, Corporal", aromas: "Noz, Almíscar", description: "Efeito quase trippy em uma indica.", growTip: "Indestrutível e forte.", medicalNote: "Estímulo sensorial." },
  "lavender": { name: "Lavender", type: "indica-dominant", lineage: "", terpenes: "", thc: "17-20%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Calmo, Zen", aromas: "Lavanda, Especiarias", description: "Flores podem ficar quase pretas.", growTip: "Sensível a excesso de nitrogênio.", medicalNote: "Ansiedade crônica." },
  // --- M ---
  "moby dick": { name: "Moby Dick", type: "sativa-dominant", lineage: "", terpenes: "", thc: "20-24%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Giga-cerebral", aromas: "Pinho, Cítrico", description: "Híbrida de elite muito vigorosa.", growTip: "Pede muitos nutrientes e luz.", medicalNote: "Estimulante de apetite." },
  "master kush": { name: "Master Kush", type: "indica", lineage: "", terpenes: "", thc: "15-18%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Corpo relaxado, Mente clara", aromas: "Cítrico, Terra", description: "Antigo favorito das cafeterias de Amsterdam.", growTip: "Bom para hidroponia.", medicalNote: "Alívio de estresse." },
  "mazar": { name: "Mazar", type: "indica", lineage: "", terpenes: "", thc: "17-20%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Dormência física", aromas: "Pinheiro, Haxixe", description: "Clássica indica robusta e resiliente.", growTip: "Planta em forma de árvore de natal.", medicalNote: "Insônia." },
  "mimosa": { name: "Mimosa", type: "hybrid", lineage: "", terpenes: "", thc: "19-22%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Energético, Feliz", aromas: "Laranja, Champagne", description: "Perfil de terpenos cítrico espetacular.", growTip: "Gosta de temperaturas diurnas amenas.", medicalNote: "Depressão matinal." },
  "magnum auto": { name: "Magnum Auto", type: "hybrid", lineage: "", terpenes: "", thc: "16-18%", cbd: "< 1%", flowerWeeks: "10-11 semanas (total)", effects: "Elevado, Criativo", aromas: "Madeira, Doce", description: "Uma das automáticas mais produtivas.", growTip: "Pode ficar grande para uma auto.", medicalNote: "Relaxamento leve." },
  // --- N ---
  "northern lights": { name: "Northern Lights", type: "indica", lineage: "Afghani x Thai", terpenes: "Mirceno", thc: "16-21%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Puro relaxamento", aromas: "Pinho, Doce", description: "Linhagem seminal, quase sem cheiro na vega.", growTip: "Excelente para iniciantes.", medicalNote: "Analgesia e sono." },
  "nebula": { name: "Nebula", type: "hybrid", lineage: "", terpenes: "", thc: "17-20%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Mental, Estelar", aromas: "Mel, Frutado", description: "Conhecida como 'Estrela da Sorte', muito resinosa.", growTip: "Responde bem a SOG.", medicalNote: "Dores leves." },
  // --- O ---
  "orange bud": { name: "Orange Bud", type: "sativa-dominant", lineage: "Skunk Selection (Afghani x Acapulco Gold x Colombian Gold)", terpenes: "Mirceno, Cariofileno, Limoneno", thc: "16-18%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Ativo, Falante", aromas: "Nectarina, Laranja", description: "Skunk clássica com sabor cítrico doce.", growTip: "Muito estável e uniforme.", medicalNote: "Falta de motivação." },
  // --- P ---
  "purple punch": { name: "Purple Punch", type: "indica", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Soninho gostoso", aromas: "Uva, Doce", description: "Cruzamento Larry OG com Granddaddy Purple.", growTip: "Planta baixa, visual roxo escuro.", medicalNote: "Pós-treino e insônia." },
  "pineapple express": { name: "Pineapple Express", type: "hybrid", lineage: "Trainwreck x Hawaiian", terpenes: "Mirceno, Cariofileno, Pineno", thc: "18-22%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Vibe de festa", aromas: "Abacaxi, Tropical", description: "Famosa no cinema, sabor tropical puro.", growTip: "Resistente a fungos.", medicalNote: "Estresse e ansiedade." },
  "purple haze": { name: "Purple Haze", type: "sativa", lineage: "", terpenes: "", thc: "16-20%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Trippy, Visual", aromas: "Baga, Doce", description: "Haze clássica de visual vibrante.", growTip: "Precisa de luz intensa para cor.", medicalNote: "Humor." },
  "power plant": { name: "Power Plant", type: "sativa", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Social, Elevado", aromas: "Pimenta, Terra", description: "Sativa africana de grande rendimento.", growTip: "Vigorosa e muito produtiva.", medicalNote: "Fadiga." },
  // --- Q ---
  "querkle": { name: "Querkle", type: "indica", lineage: "", terpenes: "", thc: "17-20%", cbd: "< 1%", flowerWeeks: "8 semanas", effects: "Físico pesado", aromas: "Uva, Café", description: "Híbrida de visual roxo e sabor frutado denso.", growTip: "Responde bem a LST.", medicalNote: "Dores musculares." },
  // --- R ---
  "runtz": { name: "Runtz", type: "hybrid", lineage: "", terpenes: "", thc: "24-29%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Extrema euforia", aromas: "Bala, Frutas", description: "Cruzamento Zkittlez x Gelato. Sucesso absoluto.", growTip: "Gosta de alimentação rica.", medicalNote: "Bem-estar geral." },
  "royal gorilla": { name: "Royal Gorilla", type: "hybrid", lineage: "", terpenes: "", thc: "25-27%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Forte, Colante", aromas: "Pinheiro, Terra", description: "A versão da RQS para a Gorilla Glue #4.", growTip: "Resina abundante.", medicalNote: "Dor e estresse." },
  // --- S ---
  "super lemon haze": { name: "Super Lemon Haze", type: "sativa", lineage: "Lemon Skunk x Super Silver Haze", terpenes: "Terpinoleno, Cariofileno, Limoneno", thc: "19-25%", cbd: "< 1%", flowerWeeks: "10-12 semanas", effects: "Foco, Criativo", aromas: "Limão, Doce", description: "Sativa cítrica premiada mundialmente.", growTip: "Pede muito P-K na floração.", medicalNote: "Depressão funcional." },
  "sour diesel": { name: "Sour Diesel", type: "sativa", lineage: "Chemdog x Super Skunk", terpenes: "Cariofileno", thc: "20-25%", cbd: "< 1%", flowerWeeks: "10-11 semanas", effects: "Gasolina mental", aromas: "Diesel, Ácido", description: "Estimulante cerebral lendário.", growTip: "Gosta de muito nitrogênio na vega.", medicalNote: "Melhora humor." },
  "skywalker og": { name: "Skywalker OG", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "No espaço", aromas: "Pinheiro, Combustível", description: "OG Kush super relaxante e potente.", growTip: "Pode ser sensível a pragas.", medicalNote: "Analgesia poderosa." },
  "strawberry cough": { name: "Strawberry Cough", type: "sativa", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Feliz, Social", aromas: "Morango puro", description: "Famosa pelo sabor doce de fruta.", growTip: "Fácil de treinar (LST/FIM).", medicalNote: "Ansiedade social." },
  "skunk #1": { name: "Skunk #1", type: "hybrid", lineage: "", terpenes: "", thc: "15-19%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Alegre, Fome", aromas: "Almiscarado, Doce", description: "A mãe das híbridas modernas.", growTip: "Muito versátil e estável.", medicalNote: "Apetite." },
  "silver haze": { name: "Silver Haze", type: "sativa", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "10-11 semanas", effects: "Cerebral, Ativo", aromas: "Pimenta, Pinheiro", description: "Sativa clássica com brilho de prata.", growTip: "Não deixe crescer demais na vega.", medicalNote: "Foco." },
  "slurricane": { name: "Slurricane", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-28%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Sedativo", aromas: "Baga, Cremoso", description: "Cruzamento Do-Si-Dos x Purple Punch.", growTip: "Visual escuro e tricomas gigantes.", medicalNote: "Dor crônica." },
  "somango": { name: "Somango", type: "indica-dominant", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Feliz, Relaxado", aromas: "Manga, Tropical", description: "Junção de Super Skunk x Jack Herer.", growTip: "Formato arbustivo.", medicalNote: "Estresse." },
  // --- T ---
  "trainwreck": { name: "Trainwreck", type: "sativa-dominant", lineage: "", terpenes: "", thc: "18-25%", cbd: "< 1%", flowerWeeks: "8-10 semanas", effects: "Euforia súbita", aromas: "Pinho, Limão", description: "Efeito cerebral rápido e devastador.", growTip: "Pode ficar desengonçada, use amarras.", medicalNote: "Enxaqueca." },
  "tangerine dream": { name: "Tangerine Dream", type: "sativa-dominant", lineage: "", terpenes: "", thc: "20-23%", cbd: "1-2%", flowerWeeks: "9-10 semanas", effects: "Ativo, Focado", aromas: "Tangerina, Cítrico", description: "Ganhadora da Cup, aroma cítrico autêntico.", growTip: "Resistente a variações de clima.", medicalNote: "Tensão muscular." },
  "tropicana cookies": { name: "Tropicana Cookies", type: "hybrid", lineage: "", terpenes: "", thc: "20-22%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Social, Feliz", aromas: "Laranja, Cookies", description: "Conhecida pela cor roxa quase negra.", growTip: "Aroma cítrico domina o grow.", medicalNote: "Desânimo." },
  // --- W ---
  "wedding cake": { name: "Wedding Cake", type: "indica-dominant", lineage: "Triangle Kush x Animal Mints", terpenes: "Cariofileno", thc: "23-27%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Felicidade, Relaxado", aromas: "Baunilha, Doce", description: "Buds densos e açúcarados como um bolo.", growTip: "Precisa de boa circulação de ar.", medicalNote: "Insônia." },
  "white widow": { name: "White Widow", type: "hybrid", lineage: "Brazilian Sativa x South Indian Indica", terpenes: "Mirceno", thc: "18-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Feliz, Comunicativo", aromas: "Madeira, Pinho", description: "Clássica coberta por resina branca.", growTip: "Suporta variações de temperatura.", medicalNote: "Ansiedade." },
  "wedding glue": { name: "Wedding Glue", type: "hybrid", lineage: "", terpenes: "", thc: "23-26%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Equilibrado, Forte", aromas: "Doce, Terroso", description: "Maturidade rápida e alta potência.", growTip: "Buds muito compactos.", medicalNote: "Estresse diário." },
  // --- Z ---
  "zkittlez": { name: "Zkittlez", type: "indica-dominant", lineage: "Grape Ape x Grapefruit x Unknown", terpenes: "Cariofileno, Linalol, Humuleno", thc: "19-23%", cbd: "< 1%", flowerWeeks: "8-10 semanas", effects: "Pura alegria", aromas: "Bala, Frutas", description: "Sabor doce inconfundível.", growTip: "Responde bem a defoliação moderada.", medicalNote: "Gestão do estresse." },
  "zake": { name: "Zake", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-24%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Relaxamento físico", aromas: "Doce, Gasolina", description: "Linhagem moderna muito resinosa.", growTip: "Vigorous no vegetativo.", medicalNote: "Analgesia." },
  // --- ADDITIONAL BATCH ---
  "pineapple chunk": { name: "Pineapple Chunk", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-25%", cbd: "1%", flowerWeeks: "8-9 semanas", effects: "Eufórico, Pesado", aromas: "Abacaxi, Queijo, Terra", description: "Cruzamento Barney's Farm: Pineapple x Skunk #1 x Cheese.", growTip: "Planta baixa, enorme produção secundária.", medicalNote: "Alívio de dor." },
  "ice cream cake": { name: "Ice Cream Cake", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Relaxado, Sonolento", aromas: "Doce, Baunilha, Cremoso", description: "Wedding Cake x Gelato #33. Sabor de sobremesa pura.", growTip: "Gosta de temperaturas estáveis.", medicalNote: "Insônia e ansiedade." },
  "mimosa evo": { name: "Mimosa Evo", type: "sativa-dominant", lineage: "", terpenes: "", thc: "24-30%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Zest, Energético", aromas: "Cítrico, Tangerina", description: "Evolução da Mimosa original, potência extrema.", growTip: "Pode atingir grandes alturas no outdoor.", medicalNote: "Fadiga matinal." },
  "hulkberry": { name: "Hulkberry", type: "sativa-dominant", lineage: "", terpenes: "", thc: "27-28%", cbd: "< 1%", flowerWeeks: "9-11 semanas", effects: "Cerebral, Forte", aromas: "Diesel, Bagas", description: "A versão da RQS da Bruce Banner #3.", growTip: "Muita luz necessária.", medicalNote: "Dores intensas." },
  "green gelato": { name: "Green Gelato", type: "hybrid", lineage: "", terpenes: "", thc: "25-27%", cbd: "< 1%", flowerWeeks: "8-10 semanas", effects: "Relaxado, Eufórico", aromas: "Biscoito, Doce", description: "Sunset Sherbet x Thin Mint Girl Scout Cookies.", growTip: "Gosta de técnicas como Topping e LST.", medicalNote: "Ansiolítico." },
  "lemon shining silver haze": { name: "Lemon Shining Silver Haze", type: "sativa", lineage: "", terpenes: "", thc: "21-25%", cbd: "< 1%", flowerWeeks: "9-11 semanas", effects: "Energético, Brilhante", aromas: "Limão, Doce", description: "Uma Haze cítrica muito potente da RQS.", growTip: "Pode esticar bastante na flora.", medicalNote: "Foco mental." },
  "shishkaberry": { name: "Shishkaberry", type: "indica", lineage: "", terpenes: "", thc: "18-24%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Relaxado, Feliz", aromas: "Frutado, Terroso", description: "Indica clássica com aroma de bagas.", growTip: "Resistente a pragas e mofo.", medicalNote: "Relaxamento pós-treino." },
  "purple punch auto": { name: "Purple Punch Auto", type: "indica", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "9 semanas (total)", effects: "Suave, Relax", aromas: "Doce de Uva", description: "Versão rápida da lendária Purple Punch.", growTip: "Fácil de esconder devido ao tamanho pequeno.", medicalNote: "Sono leve." },
  "sherbet queen": { name: "Sherbet Queen", type: "indica-dominant", lineage: "", terpenes: "", thc: "24%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Dormência física", aromas: "Frutado, Doce", description: "Sunset Sherbet x Pink Panties. Relaxamento profundo.", growTip: "Gosta de alimentação equilibrada.", medicalNote: "Dores crônicas." },
  "fat banana": { name: "Fat Banana", type: "indica", lineage: "", terpenes: "", thc: "25%", cbd: "< 1%", flowerWeeks: "8-10 semanas", effects: "Couch-lock", aromas: "Limão, Banana", description: "Uma das indica mais potentes da atualidade.", growTip: "Pode produzir colas gigantes no topo.", medicalNote: "Apetite e sono." },
  "wedding glue auto": { name: "Wedding Glue Auto", type: "hybrid", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Forte, Equilibrado", aromas: "Sorvete, Gasolina", description: "Rapidez auto com genética de elite.", growTip: "Buds brancos de tanta resina.", medicalNote: "Estresse." },
  "gorilla cookies auto": { name: "Gorilla Cookies Auto", type: "hybrid", lineage: "", terpenes: "", thc: "25-28%", cbd: "< 1%", flowerWeeks: "10 semanas (total)", effects: "Eufórico, Pesado", aromas: "Menta, Baga", description: "Cruzamento de dois gigantes em versão auto.", growTip: "Muito vigorosa, aceita bem treinamento.", medicalNote: "Analgesia potente." },
  "strawberry pie auto": { name: "Strawberry Pie Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "26%", cbd: "< 1%", flowerWeeks: "8-9 semanas (total)", effects: "Suave, Corporal", aromas: "Morango, Massa", description: "Sabor de torta de morango em ciclo recorde.", growTip: "Planta muito compacta e densa.", medicalNote: "Ansiedade leve." },
  "mimosa cake auto": { name: "Mimosa Cake Auto", type: "sativa-dominant", lineage: "", terpenes: "", thc: "24-26%", cbd: "< 1%", flowerWeeks: "9 semanas (total)", effects: "Energético, Criativo", aromas: "Laranja, Bolo", description: "Visual deslumbrante e efeito 'up'.", growTip: "Responde bem a LST.", medicalNote: "Fadiga." },
  "guava jelly": { name: "Guava Jelly", type: "hybrid", lineage: "", terpenes: "", thc: "20-22%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Feliz, Relaxado", aromas: "Goiaba, Tropical", description: "Sabor tropical exótico e doce.", growTip: "Resistente a variações térmicas.", medicalNote: "Humor." },
  "zkittlez glue": { name: "Zkittlez Glue", type: "hybrid", lineage: "", terpenes: "", thc: "22-24%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Pura euforia", aromas: "Bala, Pinheiro", description: "Sabor doce da Zkittlez com a resina da Gorilla.", growTip: "Muito resinosa, boa para haxixe.", medicalNote: "Bem-estar." },
  "pineapple express auto": { name: "Pineapple Express Auto", type: "hybrid", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "8-9 semanas (total)", effects: "Tropical, Social", aromas: "Abacaxi", description: "A queridinha do cinema em versão para preguiçosos.", growTip: "Curta e discreta.", medicalNote: "Ansiedade social." },
  "bruce banner #3": { name: "Bruce Banner #3", type: "sativa-dominant", lineage: "", terpenes: "", thc: "25-30%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Incrível energia", aromas: "Diesel, Morango", description: "Fenótipo mais potente e desejado.", growTip: "Precisa de muito espaço raízes.", medicalNote: "Dor intensa." },
  "ghost og": { name: "Ghost OG", type: "hybrid", lineage: "", terpenes: "", thc: "20-24%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Corpo e Mente", aromas: "Cítrico, Pinheiro", description: "Uma das variações OG mais equilibradas.", growTip: "Sensível a mofo, ventile bem.", medicalNote: "Stress." },
  "sfv og": { name: "SFV OG", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Analgesia, Sedação", aromas: "Limão, Pinho", description: "San Fernando Valley OG, clássica da Califórnia.", growTip: "Pode ser sensível a overfeeding.", medicalNote: "Dores de coluna." },
  "fire og": { name: "Fire OG", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Relaxamento total", aromas: "Limão, Pinho", description: "Considerada uma das OG's mais potentes.", growTip: "Prefere ser cultivada em solo orgânico.", medicalNote: "Insônia." },
  "tahoe og": { name: "Tahoe OG", type: "hybrid", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Sedação, Euforia", aromas: "Pinheiro, Terra", description: "Ideal para dias nublados ou noites em casa.", growTip: "Muito resinosa no final.", medicalNote: "Ansiedade e Dor." },
  "triangle kush": { name: "Triangle Kush", type: "indica", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Mental, Relaxado", aromas: "Diesel, Terra", description: "Originária da Flórida, base de muitas genéticas modernas.", growTip: "Gosta de podas baixas.", medicalNote: "Criatividade e Relaxamento." },
  "biscotti mintz": { name: "Biscotti Mintz", type: "indica-dominant", lineage: "", terpenes: "", thc: "25-30%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Mente clara, Corpo Relaxado", aromas: "Menta, Biscoito", description: "Visual roxo quase preto no final.", growTip: "Crescimento explosivo lateral.", medicalNote: "Ansiedade e inflamação." },
  "Critical Purple Auto": { name: "Critical Purple Auto", type: "indica", lineage: "", terpenes: "", thc: "20-25%", cbd: "< 1%", flowerWeeks: "10-11 semanas (total)", effects: "Sedativo", aromas: "Uva, Terra", description: "Visual roxo fascinante em ciclo auto.", growTip: "Resistente e fácil.", medicalNote: "Dores articulares." },
  "gelat.og": { name: "Gelat.OG", type: "indica-dominant", lineage: "", terpenes: "", thc: "25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Felicidade, Relaxado", aromas: "Biscoito, Limão", description: "Mistura de Gelato com OG Kush da Seedsman.", growTip: "Muito fácil de cultivar em interior.", medicalNote: "Estresse." },
  "gorilla sherbet": { name: "Gorilla Sherbet", type: "indica-dominant", lineage: "", terpenes: "", thc: "22-25%", cbd: "< 1%", flowerWeeks: "9 semanas", effects: "Docinho, Relaxado", aromas: "Frutado, Cookies", description: "Cruzamento de Gorilla Glue x Sunset Sherbet.", growTip: "Flores muito aromáticas, use exaustor.", medicalNote: "Falta de humor." },
  "do-si-dos 33": { name: "Do-Si-Dos #33", type: "indica-dominant", lineage: "", terpenes: "", thc: "22-25%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Estimulante e depois Relax", aromas: "Lima, Especiarias", description: "A famosa versão #33 da Barney's Farm.", growTip: "Pode ficar bem colorida no final.", medicalNote: "Espasmos musculares." },
  "wedding cake auto": { name: "Wedding Cake Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-24%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Sorriso no rosto", aromas: "Baunilha, Doce", description: "Festiva e rápida, muito açúcarada.", growTip: "Suporta bem climas quentes.", medicalNote: "Depressão." },
  "forbidden fruit auto": { name: "Forbidden Fruit Auto", type: "indica", lineage: "", terpenes: "", thc: "20-22%", cbd: "< 1%", flowerWeeks: "9 semanas (total)", effects: "Frutado e Relax", aromas: "Maracujá, Manga", description: "Visual roxo e aroma tropical intenso.", growTip: "Gosta de LST suave.", medicalNote: "Estresse." },
  "stardawg auto": { name: "Stardawg Auto", type: "hybrid", lineage: "", terpenes: "", thc: "22-24%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Eufórico, Social", aromas: "Diesel, Pinho", description: "Visual incrível, parece coberta de diamantes.", growTip: "Pode ser alimentada com níveis altos de nutrientes.", medicalNote: "Fadiga social." },
  "lemon pie auto": { name: "Lemon Pie Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "24%", cbd: "< 1%", flowerWeeks: "8-9 semanas (total)", effects: "Equilibrado", aromas: "Torta de limão", description: "Buds verde-lima com aroma cítrico doce.", growTip: "Não precisa de muito espaço vertical.", medicalNote: "Ansiedade." },
  "gelato cookies": { name: "Gelato Cookies", type: "hybrid", lineage: "", terpenes: "", thc: "20-24%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Felicidade Criativa", aromas: "Cremoso, Biscoito", description: "União das duas linhagens mais amadas.", growTip: "Exige poda de ramos baixos.", medicalNote: "Estresse." },
  "Critical mass auto": { name: "Critical Mass Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "18-20%", cbd: "1%", flowerWeeks: "9-10 semanas (total)", effects: "Corpo relaxado", aromas: "Skunk, Doce", description: "Rendimento garantido em pouco tempo.", growTip: "Excelente para iniciantes.", medicalNote: "Apetite." },
  "orange sherbet auto": { name: "Orange Sherbet Auto", type: "sativa-dominant", lineage: "", terpenes: "", thc: "22-24%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Energia Social", aromas: "Laranja Sorbet", description: "Aroma cítrico doce e visual alaranjado.", growTip: "Muito vigorosa, estica bem.", medicalNote: "Desânimo." },
  "purple lemonade auto": { name: "Purple Lemonade Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "24%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Relaxado, Elevado", aromas: "Limão, Baga", description: "A genética roxa mais famosa da FastBuds.", growTip: "Cor roxa profunda garantida.", medicalNote: "Estresse." },
  "six shooter auto": { name: "Six Shooter Auto", type: "sativa-dominant", lineage: "", terpenes: "", thc: "21-23%", cbd: "< 1%", flowerWeeks: "10 semanas (total)", effects: "Potente, Explosivo", aromas: "Incenso, Pinho", description: "Uma das automáticas mais rápidas e fortes.", growTip: "Ótima para SOG.", medicalNote: "Fadiga crônica." },
  "west coast og auto": { name: "West Coast OG Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "21-23%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Couch-lock Suave", aromas: "Pinho, Limão", description: "A versão auto da OG Kush clássica.", growTip: "Planta firme e estável.", medicalNote: "Ansiedade." },
  "gsc auto": { name: "GSC Auto", type: "indica-dominant", lineage: "", terpenes: "", thc: "20-22%", cbd: "< 1%", flowerWeeks: "9-10 semanas (total)", effects: "Felicidade Social", aromas: "Cookies, Menta", description: "Toda a potência da Cookies no seu PC grow.", growTip: "Não transplante.", medicalNote: "Stress." },
  "original bubblegum": { name: "Original Bubblegum", type: "hybrid", lineage: "", terpenes: "", thc: "16-19%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Eufórico, Relaxado", aromas: "Chiclete, Doce", description: "Sabor doce inconfundível de chiclete tutti-frutti.", growTip: "Resistente a variações térmicas.", medicalNote: "Bem-estar." },
  "hindu kush auto": { name: "Hindu Kush Auto", type: "indica", lineage: "", terpenes: "", thc: "16-18%", cbd: "< 1%", flowerWeeks: "8-9 semanas (total)", effects: "Relaxamento Zen", aromas: "Terroso, Especiarias", description: "Pura indica em versão miniatura.", growTip: "Discreta e rápida.", medicalNote: "Tensão muscular." },
  "chemdawg auto": { name: "Chemdawg Auto", type: "hybrid", lineage: "", terpenes: "", thc: "20-22%", cbd: "< 1%", flowerWeeks: "9 semanas (total)", effects: "Mental e Físico", aromas: "Diesel, Químico", description: "Aroma forte e pegada firme.", growTip: "Filtros de carvão obrigatórios.", medicalNote: "Doenças crônicas." },
  // --- LANDRACES & CLASSICS ---
  "manga rosa": { name: "Manga Rosa", type: "sativa", lineage: "Landrace Brasileira (Nordeste)", terpenes: "Terpinoleno, Mirceno", thc: "15-20%", cbd: "< 1%", flowerWeeks: "12-14 semanas", effects: "Eufórico, Mental, Ativo", aromas: "Frutado, Manga, Doce", description: "Lendária landrace brasileira do Nordeste. Efeito cerebral límpido.", growTip: "Cresce muito, exige paciência na flora longa.", medicalNote: "Fadiga e depressão." },
  "santa maria": { name: "Santa Maria", type: "sativa", lineage: "Landrace Brasileira x Mexican Haze x Silver Pearl", terpenes: "Limoneno, Mirceno, Cariofileno", thc: "16-19%", cbd: "< 1%", flowerWeeks: "11-12 semanas", effects: "Espiritual, Meditativo", aromas: "Floral, Ervas, Doce", description: "Clássica brasileira usada em contextos espirituais. Efeito suave.", growTip: "Gosta de solos orgânicos ricos.", medicalNote: "Ansiedade and meditação." },
  "colombiana gold": { name: "Colombian Gold", type: "sativa", lineage: "Landrace Colombiana (Santa Marta)", terpenes: "Mirceno, Limoneno, Pineno", thc: "15-20%", cbd: "< 1%", flowerWeeks: "12-14 semanas", effects: "Energético, Focado", aromas: "Limão, Especiarias, Skunk", description: "Landrace clássica da Colômbia, famosa nos anos 70.", growTip: "Muito resistente ao calor.", medicalNote: "Aumenta o foco." },
  "acapulco gold": { name: "Acapulco Gold", type: "sativa-dominant", lineage: "Landrace Mexicana", terpenes: "Mirceno, Cariofileno, Limoneno", thc: "15-23%", cbd: "< 1%", flowerWeeks: "10-11 semanas", effects: "Eufórico, Feliz", aromas: "Terra, Doce, Café", description: "Famosa landrace mexicana de visual dourado.", growTip: "Desenvolve buds longos e resinosos.", medicalNote: "Alívio de estresse." },
  "panama red": { name: "Panama Red", type: "sativa", lineage: "Landrace Panamenha", terpenes: "Mirceno", thc: "16-20%", cbd: "< 1%", flowerWeeks: "11-13 semanas", effects: "Energético, Falante", aromas: "Terroso, Amargo", description: "Ícone dos anos 60, visual avermelhado no final.", growTip: "Sensível a excesso de umidade.", medicalNote: "Fadiga social." },
  "lambs bread": { name: "Lamb's Bread", type: "sativa", lineage: "", terpenes: "", thc: "16-21%", cbd: "< 1%", flowerWeeks: "10-12 semanas", effects: "Energético, Criativo", aromas: "Limão, Pinheiro", description: "Favorita de Bob Marley, landrace jamaicana.", growTip: "Gosta de climas tropicais e úmidos.", medicalNote: "Depressão e estresse." },
  "malawi gold": { name: "Malawi Gold", type: "sativa", lineage: "", terpenes: "", thc: "18-22%", cbd: "< 1%", flowerWeeks: "13-16 semanas", effects: "Efeito giga-cerebral", aromas: "Picante, Mel, Limão", description: "Uma das sativas mais potentes da África.", growTip: "Floração extremamente longa.", medicalNote: "Foco profundo." },
  "pck": { name: "Pakistan Chitral Kush", type: "indica", lineage: "", terpenes: "", thc: "15-18%", cbd: "1-2%", flowerWeeks: "8-9 semanas", effects: "Relaxamento Zen", aromas: "Baga, Caramelo", description: "Famosa pelas suas cores roxas e resina de elite.", growTip: "Muito resistente a mofo e frio.", medicalNote: "Dores leves e ansiedade." },
  "ketama": { name: "Ketama", type: "indica", lineage: "", terpenes: "", thc: "15-17%", cbd: "1%", flowerWeeks: "7-8 semanas", effects: "Relaxado, Físico", aromas: "Haxixe marroquino, Insenso", description: "Originária do Marrocos, base do melhor haxixe do mundo.", growTip: "Resistente à seca e ao calor.", medicalNote: "Relaxamento profundo." },
  "g13": { name: "G13", type: "indica", lineage: "", terpenes: "", thc: "20-22%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Pesado, Narcótico", aromas: "Madeira, Terra", description: "Reza a lenda que foi criada pelo governo dos EUA.", growTip: "Planta densa e muito potente.", medicalNote: "Dores severas e insônia." },
  "chronic": { name: "Chronic", type: "hybrid", lineage: "", terpenes: "", thc: "18-20%", cbd: "< 1%", flowerWeeks: "8-9 semanas", effects: "Relaxo Equilibrado", aromas: "Doce, Mel, Skunk", description: "Famosa pelo rendimento massivo sem perder qualidade.", growTip: "Evite podas apicais; prefere crescer uma cola gigante.", medicalNote: "Estresse." },
  "big bud": { name: "Big Bud", type: "indica-dominant", lineage: "", terpenes: "", thc: "15-18%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Relaxado, Com Fome", aromas: "Terroso, Especiarias", description: "Famosa mundialmente pelo tamanho dos seus buds.", growTip: "Precisa de suporte para os galhos não quebrarem.", medicalNote: "Falta de apetite." },
  "mazar-i-sharif": { name: "Mazar-i-Sharif", type: "indica", lineage: "", terpenes: "", thc: "17-20%", cbd: "1%", flowerWeeks: "8-9 semanas", effects: "Meditativo, Pesado", aromas: "Especiarias, Pinho", description: "Indica gigante e lendária do Afeganistão.", growTip: "Muito vigorosa, pode atingir 2 metros.", medicalNote: "Analgesia profunda." },
  // --- CBD & MEDICINAL ---
  "cannatonic": { name: "Cannatonic", type: "hybrid", lineage: "", terpenes: "", thc: "6%", cbd: "6-17%", flowerWeeks: "9-10 semanas", effects: "Relaxo sem chapar, Focado", aromas: "Terra, Pinheiro, Cítrico", description: "Uma das pioneiras no movimento CBD. Proporção 1:1 ou superior.", growTip: "Pode ser sensível a mudanças bruscas de temperatura.", medicalNote: "Ansiedade e espasmos." },
  "harlequin": { name: "Harlequin", type: "sativa-dominant", lineage: "", terpenes: "", thc: "4-7%", cbd: "8-16%", flowerWeeks: "8-9 semanas", effects: "Mente limpa, Relaxado", aromas: "Terra, Madeira, Doce", description: "Famosa pela sua consistência em produzir CBD alto.", growTip: "Gosta de luz moderada e regas constantes.", medicalNote: "Dor e ansiedade." },
  "acdc": { name: "ACDC", type: "sativa-dominant", lineage: "", terpenes: "", thc: "1-6%", cbd: "15-20%", flowerWeeks: "9-10 semanas", effects: "Relaxamento total, Sem psicoatividade", aromas: "Pinheiro, Terra, Doce", description: "Extremamente alta em CBD, quase nada de THC.", growTip: "Planta vigorosa mas exige atenção a nutrientes.", medicalNote: "Epilepsia e inflamação severa." },
  "sour tsunami": { name: "Sour Tsunami", type: "hybrid", lineage: "", terpenes: "", thc: "1-10%", cbd: "10-11%", flowerWeeks: "9 semanas", effects: "Relaxado, Feliz", aromas: "Diesel, Pinheiro, Doce", description: "Criada especificamente por Lawrence Ringo para CBD.", growTip: "Resiliente e fácil de treinar.", medicalNote: "Dores articulares." },
  "charlottes web": { name: "Charlotte's Web", type: "sativa-dominant", lineage: "", terpenes: "", thc: "< 1%", cbd: "15-20%", flowerWeeks: "9-10 semanas", effects: "Calmo, Mente clara", aromas: "Pinho, Terra", description: "A strain que iniciou a revolução do CBD medicinal.", growTip: "Resistente, cresce bem em outdoor também.", medicalNote: "Convulsões e autismo." },
  "critical mass cbd": { name: "Critical Mass CBD", type: "indica-dominant", lineage: "", terpenes: "", thc: "5%", cbd: "5%", flowerWeeks: "8 semanas", effects: "Suave, Relaxado", aromas: "Mel, Frutado", description: "Versão equilibrada da famosa Critical Mass.", growTip: "Rendimento excelente para extrações medicinais.", medicalNote: "Bem-estar geral." },
  // --- MORE FAVORITES ---
  "cream caramel": { name: "Cream Caramel", type: "indica", lineage: "", terpenes: "", thc: "15-20%", cbd: "1%", flowerWeeks: "8-9 semanas", effects: "Relaxado, Doce", aromas: "Caramelo, Café, Doce", description: "Vencedora de inúmeras taças, sabor de sobremesa.", growTip: "Desenvolve buds muito densos e aromáticos.", medicalNote: "Estresse e sono." },
  "green poison": { name: "Green Poison", type: "indica-dominant", lineage: "", terpenes: "", thc: "15-20%", cbd: "< 1%", flowerWeeks: "7 semanas", effects: "Felicidade Intensa", aromas: "Frutado, Doce, Skunk", description: "Extremamente rápida e produtiva.", growTip: "Ideal para colheitas rápidas antes do outono.", medicalNote: "Falta de apetite." },
  "sugar black rose": { name: "Sugar Black Rose", type: "indica", lineage: "", terpenes: "", thc: "18-25%", cbd: "< 1%", flowerWeeks: "7-8 semanas", effects: "Narcótico, Relaxado", aromas: "Frutas Doces, Flores", description: "Uma das indica mais premiadas do mundo.", growTip: "Gosta de podas e treinamento lateral.", medicalNote: "Dores musculares e insônia." },
  "jack 47": { name: "Jack 47", type: "hybrid", lineage: "", terpenes: "", thc: "18-24%", cbd: "< 1%", flowerWeeks: "9-10 semanas", effects: "Eufórico, Forte", aromas: "Cítrico, Madeira, Incenso", description: "Cruzamento de Jack Herer x AK-47. Vigor híbrido.", growTip: "Muito ramificada e produtiva.", medicalNote: "Depressão." }
};



